# @package target
# PDL1 target configuration

target_name: "pdl1"
target_pdb_path: "pdbs/pdl1.pdb"
# Ensure chains in PDB have the right chain IDs (ideally A, B, C, etc.)
target_chain: "A"
binder_chain: "B"
target_hotspots: "A37,A39,A41,A96,A98"

# Residue to be used for Chai-1 distance constraint ({residue 1-letter}{res. num.}). 
# Can delete or set to None if no constraint. Residue should be in chain A
hotspot_residue: "W40"